### ISSUE TITLE
Vectorizing different elements in CorrectionSet

### ISSUE THREAD

**Issue by jrueb** [cms-nanoAOD/correctionlib#112]
Using the b-tagging scale factors as provided here https://gitlab.cern.ch/cms-nanoAOD/jsonpog-integration/-/blob/master/POG/BTV/2016postVFP_UL/btagging.json.gz I would like to use the elements "deepJet_comb" and "deepJet_incl" of the resulting corrections set. However, which of the two I need to use depends on the flavor, which is the 3rd argument of the factors. This flavor is an array in Python, and thus in principle which element of the set to use is also determined by an array or needs to be vectorized. Coffea's BTagScaleFactor had a functionality to change between the methods ("comb", "incl", etc) depending on the flavor. Is this possible with correctionlib as well?

Below is an example of what I am doing. None of the two evaluate calls succeed because both flavors (5 and 0) are not contained in a single correction.
```python
import correctionlib
corr = correctionlib.CorrectionSet.from_file("btagging.json.gz")

corr["deepJet_comb"].evaluate("central", "M", np.array([5,0]), np.array([1.,1.]), np.array([30.,35.]))
corr["deepJet_incl"].evaluate("central", "M", np.array([5,0]), np.array([1.,1.]), np.array([30.,35.]))
```

**Comment by nsmith-** [comment]
I had the same comment when the SF were designed in https://gitlab.cern.ch/cms-nanoAOD/jsonpog-integration/-/merge_requests/32#note_4956432
I think the point was that since uncertainties are different, it may make sense to handle them separately? I agree this adds some complexity to vectorized handling of SF, but with some small extra work you could filter the jet jagged arrays before evaluating each flavor.

**Comment by nsmith-** [comment]
To be clear, this is technically possible to do with correctionlib: just insert a category node for the flavor, auto-selecting the method. But the BTV group has decided it is better to keep it explicit.
