### ISSUE TITLE
Description field in CorrectionSet

### ISSUE THREAD

**Issue by IzaakWN** [cms-nanoAOD/correctionlib#74]
As discussed in XPOG, it might be useful to have an optional description field in `CorrectionSet` to document the content, changes, and perhaps the version, e.g. here: https://github.com/cms-nanoAOD/correctionlib/blob/6c4d761ef0458ce651222341e121294073d5e8ef/src/correctionlib/schemav2.py#L351-L354
we can simply add
```
class CorrectionSet(Model):
    schema_version: Literal[VERSION] = Field(description="The overall schema version")
    corrections: List[Correction]
    description: Optional[str] = Field(
        description="A nice description of what is in this CorrectionSet means"
    )
```
Maybe for future use, a dedicated `version` field, which is also optional, to keep track of `CorrectionSet` version, could be useful, although I do not have an immediate use case for the TauPOG.

**Comment by IzaakWN** [comment]
An optional `description` field might also be useful for any other type of node (`Binning`, `Category`, `Transform`, ...) to leave extra comments/documentation. If it's optional, it should not cause extra overhead.

**Comment by nsmith-** [comment]
I was planning to keep all nodes semi-private from a user perspective. In that case I would prefer not to include descriptions for them, since the highlevel interface and inputs all have description tags. If you see some particular use case for it I'd be happy to hear it. Meanwhile I will add a description to the CorrectionSet.
